version = 1

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "docker/Dockerfile",
  ]

[[analyzers]]
name = "rust"
enabled = true

  [analyzers.meta]
  msrv = "1.30.0"

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ['nodejs']
  plugins = ['react', 'vue']
  dependency_file_paths = [
    'javascript/packages/demo-react/',
    'javascript/packages/demo-vue/',
    'javascript/packages/demo-next/',
    'javascript/packages/demo-nuxt/',
    'javascript/packages/demo-typescript/'
  ]

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/QuackatronHQ/Gigarepo"

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"